// data.js
export const departments = [
  {
    departmentId: 1,
    name: "Forensic Science",
    description: "Crime scene investigations & evidence analysis",
    isActive: true,
    profileImage: "forensic_science.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    departmentId: 2,
    name: "Digital Forensics",
    description: "Cybercrime & digital evidence",
    isActive: true,
    profileImage: "digital_forensics.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    departmentId: 3,
    name: "Ballistics",
    description: "Firearms and ammunition analysis",
    isActive: true,
    profileImage: "ballistics.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const users = [
  {
    id: 1,
    username: "detective_jon",
    password: "forensic123", // only for demo!
    firstName: "Jon",
    lastName: "Snow",
    email: "jon@forensic.com",
    phone: "1111111111",
    departmentID: 1,
    role: "admin",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "jon.png",
  },
  {
    id: 2,
    username: "agent_smith",
    password: "digital321",
    firstName: "Smith",
    lastName: "Anderson",
    email: "smith@forensic.com",
    phone: "2222222222",
    departmentID: 2,
    role: "user",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "smith.png",
  },
  {
    id: 3,
    username: "analyst_eve",
    password: "evidence456",
    firstName: "Eve",
    lastName: "Riley",
    email: "eve@forensic.com",
    phone: "3333333333",
    departmentID: 1,
    role: "user",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "eve.png",
  },
  {
    id: 4,
    username: "cyber_bob",
    password: "cyberpass",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob@forensic.com",
    phone: "4444444444",
    departmentID: 2,
    role: "user",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "bob.png",
  },
  {
    id: 5,
    username: "casey_law",
    password: "casepass",
    firstName: "Casey",
    lastName: "Lawrence",
    email: "casey@forensic.com",
    phone: "5555555555",
    departmentID: 1,
    role: "user",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "casey.png",
  },
  {
    id: 6,
    username: "maria_garcia",
    password: "maria123",
    firstName: "Maria",
    lastName: "Garcia",
    email: "maria@forensic.com",
    phone: "6666666666",
    departmentID: 3,
    role: "user",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "maria.png",
  },
  {
    id: 7,
    username: "david_chen",
    password: "david456",
    firstName: "David",
    lastName: "Chen",
    email: "david@forensic.com",
    phone: "7777777777",
    departmentID: 2,
    role: "admin",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "david.png",
  },
  {
    id: 8,
    username: "sarah_wilson",
    password: "sarah789",
    firstName: "Sarah",
    lastName: "Wilson",
    email: "sarah@forensic.com",
    phone: "8888888888",
    departmentID: 1,
    role: "user",
    isActive: false,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "sarah.png",
  },
  {
    id: 9,
    username: "michael_brown",
    password: "michael123",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael@forensic.com",
    phone: "9999999999",
    departmentID: 3,
    role: "user",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "michael.png",
  },
  {
    id: 10,
    username: "lisa_davis",
    password: "lisa456",
    firstName: "Lisa",
    lastName: "Davis",
    email: "lisa@forensic.com",
    phone: "1010101010",
    departmentID: 2,
    role: "user",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "lisa.png",
  },
  {
    id: 11,
    username: "james_miller",
    password: "james789",
    firstName: "James",
    lastName: "Miller",
    email: "james@forensic.com",
    phone: "1111111112",
    departmentID: 1,
    role: "user",
    isActive: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "james.png",
  },
  {
    id: 12,
    username: "emma_taylor",
    password: "emma123",
    firstName: "Emma",
    lastName: "Taylor",
    email: "emma@forensic.com",
    phone: "1212121212",
    departmentID: 3,
    role: "user",
    isActive: false,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profileImage: "emma.png",
  },
]; 